//
//  problem2.hpp
//  ProjectEuler
//
//  Created by Dibyaranjan Sathua on 28/06/19.
//  Copyright © 2019 Dibyaranjan Sathua. All rights reserved.
//

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 Solution: E(k) = 4E(k-1) + E(k-2)
 
*/

#ifndef problem2_hpp
#define problem2_hpp

#include <iostream>
#include <cmath>

using namespace std;

namespace P2 {
    long findNthFibo(long n);
    long findSolution2(long n);
}

#endif /* problem2_hpp */
